### PR TITLE
replaced scale with prePRocess in all chapters; fixed over/underfit e…

### PR DESCRIPTION
**Pull request by trevorcampbell**
- replaced `scale` with `preProcess` in all chapters
- made sure to do test/train *and* X/Y splits before preProc
- fixed broken under/overfit example in Ch 7

### CODE REVIEW

**Comment by ttimbers** [comment]
@trevorcampbell - what is going on with this PR?

**Comment by trevorcampbell** [comment]
> @trevorcampbell - what is going on with this PR?

Looks like it is still pending your review! If you agree with the changes (which were long enough ago now that I don't really recall, but the notes in the original message should guide) then I'd merge it into `dev` rather than `master`

**Comment by trevorcampbell** [comment]
(there are a few open issues about this, e.g. #43  )

**Comment by trevorcampbell** [comment]
I believe this PR is superceded by #55 on Tidymodels, so I'm closing it.

**Pull request closed without merging**
