### PR TITLE
forward references, new `ggplot` `dplyr` function, intended audience

### PR DESCRIPTION
**Pull request by leem44**
- addressing #131, #127, #121, #153, #183
addressed these for wrangling and index chapters here:  #143
- addressed comments here: #102
   - The items I didn't cross out: I either created a separate issue or I decided not to implement because I didn't agree or they didn't require changing (if anyone feels strongly that I should then I am happy to discuss!)

### CODE REVIEW

**Comment by leem44** [comment]
@trevorcampbell @ttimbers please have a look at these changes! Thanks!

**Comment by trevorcampbell** [comment]
@leem44 not doing a full review, but I did do a quick check for `%>%` and there are at least a few of them still remaining in the various Rmd files. I was assuming we'd introduce both options when we introduce the pipe, and then just stick with the newer one, no?

**Comment by leem44** [comment]
@trevorcampbell I did leave it in the wrangling chapter as a "here is what the old pipe looks like but we're not using it" type of thing. Did I leave it in any other chapters?

**Comment by trevorcampbell** [comment]
It appears in 01-reading, and 02-wrangling it seems that only `%>%` is introduced, and also appears in 04-version_control. Maybe not editing because some of these are part of other PRs?

**Comment by leem44** [comment]
Yes that's right -- I should have mentioned that I didn't update 04-version_control because of the pending PR

**Comment by trevorcampbell** [comment]
@leem44 two notes:

- there are now conflicts between this branch and `dev` (because I merged #146 ). For most cases we should accept the version that is now in `dev`.
- the old pipe appears in `05-...` through `08-...` (due to the merged PR #146 ) -- when resolving merge conflicts we should keep the new pipe operator

**Pull request merged**
