### PR TITLE
Wrangling chapter review

### PR DESCRIPTION
**Pull request by leem44**
@trevorcampbell @ttimbers Please have a look at this PR and let me know if I should make any changes! 
This PR addresses: #103, #160

- Note: I have *not* yet removed `map` from this chapter  -- I figure its easier to get any feedback on this, make changes and then create a branch off of this to remove `map`

### CODE REVIEW

**Comment by ttimbers** [comment]
@leem44 - I combined row and observation figure into one, as the explanation seemed to long and drawn out. Here's what the combined figure looks like:

Screen Shot 2021-09-19 at 12 07 37 PM

Is this change OK?

**Comment by ttimbers** [comment]
Also changed the vector figure to be of type character, as previously it was called an integer, but then we actually made a double vector in code... I tried to swap it to double, but then it was too confusing for a first example. Character vector is a simpler and thus better first example:
Screen Shot 2021-09-19 at 12 23 34 PM

**Comment by ttimbers** [comment]
Also changed the vector figure to be of type character, as previously it was called an integer, but then we actually made a double vector in code... I tried to swap it to double, but then it was too confusing for a first example. Character vector is a simpler and thus better first example:
Screen Shot 2021-09-19 at 12 23 34 PM

**Comment by leem44** [comment]
@ttimbers Changes look good! Only thing is the one below "Montreal" is spelled "Montreak" 

> Also changed the vector figure to be of type character, as previously it was called an integer, but then we actually made a double vector in code... I tried to swap it to double, but then it was too confusing for a first example. Character vector is a simpler and thus better first example:
> Screen Shot 2021-09-19 at 12 23 34 PM

**Comment by ttimbers** [comment]
Good catch!

**Comment by ttimbers** [comment]
I also removed loading data from the canlang package and instead get them to read the data from files. I don't think we really explain data packages and they are kind of weird, so best to leave out I think?

**Comment by leem44** [comment]
Yes, I agree with that! Makes sense!

**Comment by ttimbers** [comment]
In Fig 3.10 we illlustrate going from longer to wider, but each table is the same number of columns. Yes, this is technically something that happens, but for our first teaching case we really should have a wider dataframe that we make longer:
Screen Shot 2021-09-21 at 10 26 13 PM

Also, where did the values for commuters come from? I imagine population came from `canlang`, but I don't think that data set has commuters? Other columns we could add from `canlang` could be area? I will try to do that.

**Comment by ttimbers** [comment]
I think we should remove the `&` operator from here as we never use it elsewhere in the book or course. So it's just redundant and extra info that they do not "need" to know:
Screen Shot 2021-09-22 at 9 48 06 AM

**Comment by ttimbers** [comment]
@leem44 - I am also removing the demonstration of `filter` not working on numeric data that is in the `mutate` section, as it is rendundant to what we wrote above in the section about `convert` and `separate`.

**Comment by ttimbers** [comment]
@leem44 - in the wrangling chapter, are you OK to move the pipe to before `mutate` and after `select` and `filter`? It uses `select` and `filter` so is timely after those two. Also, then I can use the `|>` in the setup for the `as.numeric` transformation for `mutate` so the creation of the data frame with the character columns that should be numbers is a little less magical?

**Comment by ttimbers** [comment]
Simplified the example to just plot the proportion of people speaking English as the primary language at home.
Then we can skip case_when and vector recycling and keep the narrative pretty similar.

**Comment by ttimbers** [comment]
Done all sections except for `summarize` + `across` and `purrr::map*` (I did do `rowwise` which comes after these).

**Comment by ttimbers** [comment]
OK, I think we are ready to merge.  I added a bunch of images into the wrangling chapter, and re-organized the section where we do aggregation. I am pretty excited about it. @leem44 - I made quite a few changes to the wrangling chapter to (hopefully) simplify it. I hope that is OK. If there is anything I removed that you really want to keep in, please let me know and we can talk and find a way to keep it.

**Comment by ttimbers** [comment]
@leem44 gave me the go-ahead to merge, so merging!

**Pull request merged**
